In [111]:
from sklearn.datasets import load_diabetes
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import random

In [57]:
X,y=load_diabetes(return_X_y=True)

In [58]:
X.shape , y.shape

((442, 10), (442,))

In [59]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [60]:
reg=LinearRegression()
reg.fit(X_train,y_train)

LinearRegression()

In [61]:
reg.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [62]:
reg.intercept_

np.float64(151.88331005254167)

In [63]:
y_pred=reg.predict(X_test)
r2_score(y_test,y_pred)

0.4399338661568968

In [117]:
class MBGDRegressor:

  def __init__(self,lr,epochs,batch_size):
    self.coef_=None
    self.intercept_=None
    self.lr=lr
    self.epochs=epochs
    self.batch_size=batch_size

  def fit(self,X_train,y_train):
    self.intercept_=0
    self.coef_=np.ones(X_train.shape[1])

    for i in range(self.epochs):
      for j in range(int(X_train.shape[0]/self.batch_size)):
        idx = random.sample(range(X_train.shape[0]),self.batch_size)

        y_hat = np.dot(X_train[idx],self.coef_) + self.intercept_

        intercept_der = -2 * np.mean(y_train[idx] - y_hat)
        self.intercept_=self.intercept_ - (self.lr * intercept_der)

        coef_der = -2 * np.dot((y_train[idx] - y_hat),X_train[idx])
        self.coef_=self.coef_ - ((self.lr * coef_der))


  def predict(self,X_test):
    return np.dot(X_test,self.coef_) + self.intercept_


In [130]:
gd=MBGDRegressor(lr=0.1,epochs=50,batch_size=int(X_train.shape[0]/20))

In [131]:
import time

start=time.time()
gd.fit(X_train,y_train)
print('Time taken',time.time() - start)

Time taken 0.03975629806518555


In [132]:
gd.coef_

array([   7.3242723 , -222.26800766,  530.30092314,  329.26690337,
        -90.73562496, -121.98999448, -194.367179  ,   59.6389444 ,
        562.88940685,   43.82170049])

In [133]:
gd.intercept_

np.float64(151.21869629910898)

In [134]:
y_pred = gd.predict(X_test)

In [135]:
r2_score(y_test,y_pred)

0.4422861034100882

In [99]:
from sklearn.linear_model import SGDRegressor

In [140]:
reg = SGDRegressor(max_iter=100,learning_rate='constant',eta0=0.02)

In [152]:
batch_size=10

for i in range(100):
  idx=random.sample(range(X_train.shape[0]),batch_size)
  reg.partial_fit(X_train[idx],y_train[idx])

In [153]:
reg.coef_

array([  59.66678523,  -54.72192845,  316.19633603,  227.75650438,
         31.68533141,  -13.79788839, -163.0059202 ,  128.77053802,
        302.33857087,  132.33401951])

In [154]:
reg.intercept_

array([150.49534298])

In [155]:
y_pred = reg.predict(X_test)

In [156]:
r2_score(y_test,y_pred)

0.42274395729231884