## Random Number Generators

In [89]:
import numpy as np
np.random.rand(10) # returns n random numbers

array([0.4562706 , 0.27980202, 0.93289165, 0.31435135, 0.90971466,
       0.04341809, 0.70711506, 0.48388904, 0.44422106, 0.03632334])

In [92]:
np.random.seed(123) # fixes the random number as it was changing again and again
np.random.rand(10)

array([0.69646919, 0.28613933, 0.22685145, 0.55131477, 0.71946897,
       0.42310646, 0.9807642 , 0.68482974, 0.4809319 , 0.39211752])

In [113]:
from sklearn.neighbors import KNeighborsClassifier

np.random.seed(123)
y=np.array([0]*50 + [1]*50)
X=np.random.rand(100,2)

knn_model=KNeighborsClassifier(n_neighbors=3)
knn_model.fit(X,y)
knn_model.score(X,y)

0.75

In [116]:
rng1=np.random.RandomState(seed=123) # similar to random.rand()
rng1.rand(3)

array([0.69646919, 0.28613933, 0.22685145])

In [118]:
rng1=np.random.RandomState(seed=123)
np.random.rand(2) # this is not affected by RandomState and will generate random number every time

array([0.65336487, 0.99608633])

In [120]:
rng2=np.random.default_rng(seed=123) # similar to all upper options
rng2.random(3)

array([0.68235186, 0.05382102, 0.22035987])