## Creating Arrays

In [2]:
import numpy as np

In [11]:
np.ones((3,3),dtype=np.int32)


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [16]:
np.zeros((10,10),dtype=np.int64)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [23]:
help(np.ones)
   #OR
np.zeros?

Help on function ones in module numpy:

ones(shape, dtype=None, order='C', *, device=None, like=None)
    Return a new array of given shape and type, filled with ones.

    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    device : str, optional
        The device on which to place the created array. Default: None.
        For Array-API interoperability only, so must be ``"cpu"`` if passed.

        .. versionadded:: 2.0.0
    like : array_like, optional
            Reference object to allow the creation of arrays which are not
            NumPy arrays. If an array-like passed in as ``like`` supports
  

Docstring:
zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Al

In [24]:
np.zeros((4,4)) + 99

array([[99., 99., 99., 99.],
       [99., 99., 99., 99.],
       [99., 99., 99., 99.],
       [99., 99., 99., 99.]])

In [34]:
np.empty((3,3))#creating empty array    

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

creating identity matrix

In [41]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

indentity matrix with values

In [43]:
np.diag((4,4,4))  #similar to np.eye just argumnets are values in diagonal

array([[4, 0, 0],
       [0, 4, 0],
       [0, 0, 4]])

numpy.arange() function creates an array of evenly spaced values within a given interval

In [55]:
np.arange(0,100,2)  # 0 is start ,100 is stop ,2 is steps similar to range data

range(1, 100)


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

linspace() function in NumPy returns an array of evenly spaced numbers over a specified range

In [56]:
np.linspace(1,20,num=100)

array([ 1.        ,  1.19191919,  1.38383838,  1.57575758,  1.76767677,
        1.95959596,  2.15151515,  2.34343434,  2.53535354,  2.72727273,
        2.91919192,  3.11111111,  3.3030303 ,  3.49494949,  3.68686869,
        3.87878788,  4.07070707,  4.26262626,  4.45454545,  4.64646465,
        4.83838384,  5.03030303,  5.22222222,  5.41414141,  5.60606061,
        5.7979798 ,  5.98989899,  6.18181818,  6.37373737,  6.56565657,
        6.75757576,  6.94949495,  7.14141414,  7.33333333,  7.52525253,
        7.71717172,  7.90909091,  8.1010101 ,  8.29292929,  8.48484848,
        8.67676768,  8.86868687,  9.06060606,  9.25252525,  9.44444444,
        9.63636364,  9.82828283, 10.02020202, 10.21212121, 10.4040404 ,
       10.5959596 , 10.78787879, 10.97979798, 11.17171717, 11.36363636,
       11.55555556, 11.74747475, 11.93939394, 12.13131313, 12.32323232,
       12.51515152, 12.70707071, 12.8989899 , 13.09090909, 13.28282828,
       13.47474747, 13.66666667, 13.85858586, 14.05050505, 14.24

## Indexing Arrays

In [59]:
arry=np.array([1,2,3])
arry[0]

np.int64(1)

### slicing

In [63]:
arry[:2]

array([1, 2])

### 2D Array Indexing

In [69]:
arr=np.array([[1,2,3],
             [4,5,6]])

arr[0,0] #upper right

np.int64(1)

In [68]:
arr[-1,-1] #lower right

np.int64(6)

In [72]:
arr[0,:] #first row 

array([1, 2, 3])

In [76]:
arr[:,0] #first column

array([1, 4])

In [77]:
arr[:,:2] #first two column

array([[1, 2],
       [4, 5]])