## Reshaping Arrays

In [1]:
import numpy as np

In [ ]:
np.ones((28,28)).reshape(784).shape #combines rows and columns 2d to 1d arrays 28 x 28 = 784

In [21]:
arry1d=np.array([1,2,3,4,5,6])
arry2d=arry1d.reshape(2,3)
#converting 1d array to 2d (2,3) because 3*2 or 2*3=6 i.e no. of element are 6 only if we write (3,3) it gives error
arry2d

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
arry1d.reshape(-1,2) #-1 it will guess the last axes

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
arry1d.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
#2d to 1d arrays

a2d=np.array([[1,2,3],[4,5,6]])
a1d=a2d.reshape(-1) #-1 will guess the axes
a1d

array([1, 2, 3, 4, 5, 6])