## Reshaping Arrays

In [1]:
import numpy as np

In [2]:
np.ones((28,28)).reshape(784).shape #combines rows and columns 2d to 1d arrays 28 x 28 = 784

(784,)

In [3]:
arry1d=np.array([1,2,3,4,5,6])
arry2d=arry1d.reshape(2,3)
#converting 1d array to 2d (2,3) because 3*2 or 2*3=6 i.e no. of element are 6 only if we write (3,3) it gives error
arry2d

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
arry1d.reshape(-1,2) #-1 it will guess the last axes

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
arry1d.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
#2d to 1d arrays

a2d=np.array([[1,2,3],[4,5,6]])
a1d=a2d.reshape(-1) #-1 will guess the axes
        #OR
a1d=a2d.flatten() #flatten the arrays from 2d to 1d 
        #OR
a1d=a2d.ravel() # similar to above functions
a1d

array([1, 2, 3, 4, 5, 6])

Concatenate

In [7]:
ary=np.array([1,2,3])
 # stacking along first axes
np.concat((ary,ary))

array([1, 2, 3, 1, 2, 3])

In [8]:
ary=np.array([[1,2,3],[4,5,6]])
#stacking along rows axis=0
np.concat((ary,ary),axis=0).shape

(4, 3)

In [9]:
ary=np.array([[1,2,3],[4,5,6]])
#stacking along column axis=1
np.concat((ary,ary),axis=1).shape

(2, 6)