## NumPy Advanced Indexing -- Memory Views and Copies

In [12]:
import numpy as np

ary=np.array([[1,2,3],[4,5,6]])
first_row=ary[0]
first_row

array([1, 2, 3])

In [13]:
first_row+=99 #modified values of arrays also with the first_rows
ary

array([[100, 101, 102],
       [  4,   5,   6]])

In [25]:
ary1=np.array([[1,2,3],[4,5,6]])

second_row=ary1[1].copy() #this hepls to keep the orginal array as it is
second_row+=99
ary1

array([[1, 2, 3],
       [4, 5, 6]])

Slicing helps in creating copy 

In [29]:
ary1[:,[0,2]] # this type of slicing is not possible with lists in python  also creates copy

this_is_copy=ary1[:,[0,2]]
this_is_copy+=99
ary1
this_is_copy


array([[100, 102],
       [103, 105]])

In [32]:
greater_mask=ary1 >3 # gives boolean values for the value greater than the given number
greater_mask

array([[False, False, False],
       [ True,  True,  True]])

In [34]:
ary1[greater_mask] #tkes the indexing as argument and return the value for True

array([4, 5, 6])

In [35]:
ary1[(ary1 >3 ) & (ary1%2==0)]

array([4, 6])