# Array Math and Universal Functions

enumerate() function is a built-in utility that adds a counter to any iterable (like a list, tuple, or string) and returns it as an enumerate object. This allows you to easily access both the index and the value of an item while looping, making the code more readable and concise than managing a counter manually

In [30]:
lst=[[1,2,3],
     [4,5,6]]

for row_index,row_value in enumerate(lst):
    for col_index,col_value in enumerate(row_value):
        lst[row_index][col_index] +=1

lst

[[2, 3, 4], [5, 6, 7]]

list comprehensions

In [31]:
[[cell +1 for cell in row]for row in lst]

[[3, 4, 5], [6, 7, 8]]

In [32]:
import numpy as np

#func for element wise addition

ary=np.array([[1,2,3],[4,5,6]])
ary=np.add(ary,1)   #or replace ad with sub,exp,sqrt etc
    #or
ary + 1

array([[3, 4, 5],
       [6, 7, 8]])

In [33]:
ary ** 2

array([[ 4,  9, 16],
       [25, 36, 49]])

Reduce Function

In [34]:
ary=np.array([[1,2,3],[7,5,6]])
np.add.reduce(ary,axis=0) #column Sums axis=0 means rows

array([8, 7, 9])

In [35]:
np.add.reduce(ary,axis=1) #row sums axis=1 means rows

array([ 6, 18])

In [36]:
ary.sum(axis=0) # similar to the above func

array([8, 7, 9])

In [37]:
ary.sum() # sum of the whole array

np.int64(24)

Statistics Functions

In [45]:
np.mean(ary)
np.std(ary)
np.var(ary)
np.sort(ary)
print(np.argsort(ary)) # returns indices that would sort the arrays
np.min(ary)
np.max(ary)
np.argmin(ary)#returns the indice of min element
np.argmax(ary)#returns the indice of max element
ary2=([1,2,1])
np.array_equal(ary,ary2)# checks if two arrays are eqaual


[[0 1 2]
 [1 2 0]]


False