## Comparing List vs Numpy array

In [2]:
def python_forloop_list_approach(x,w):
    z=0
    for i in range(len(x)):
        z+= x[i] * w[i]
    return z

a=[1.,2.,3.]
b=[4.,5.,6.]
print(python_forloop_list_approach(a,b))

32.0


In [4]:
large_a=list(range(1000))
large_b=list(range(1000))

%timeit python_forloop_list_approach(large_a,large_b)

105 μs ± 6.18 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [21]:
import numpy as np

def numpy_dotproduct_approach(x,w):
    return x@(w)
               #OR x.dot == x@
def numpy_dotproduct_approach(x,w):
    return x.dot(w)

a=np.array([1.,2.,3.])
b=np.array([4.,5.,6.])

print(numpy_dotproduct_approach(a,b))

32.0


In [18]:
large_a=np.arange(10000)
large_b=np.arange(10000)

%timeit numpy_dotproduct_approach(large_a,large_b)

9.38 μs ± 641 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


## N-dimensional Arrays

2-dimensional Arrays

In [32]:
lst=[[1,2,3],[4,5,6]]
arry2d=np.array(lst)
arry2d

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
arry2d[1,2]

np.int64(6)

In [34]:
arry2d.dtype

dtype('int64')

In [35]:
float32_ary=arry2d.astype(np.float32)
float32_ary

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [36]:
float32_ary.dtype

dtype('float32')

In [40]:
np.array([1.00000002]).astype(np.float16) #convertions of datatype

array([1.], dtype=float16)

In [43]:
arry2d.ndim #number of dimension of array

2

In [46]:
arry2d.shape #dimension of array

(2, 3)