## Linear Algebra with Numpy Arrays

In [88]:
import numpy as np

Row vector has 1 row and multiple columns

In [89]:
row_vector=np.array([1,2,3]) 
row_vector.shape

(3,)

In [90]:
column_vector=np.array([1,2,3])
column_vector

array([1, 2, 3])

In [103]:
column_vector[:,np.newaxis]

array([[[1, 2, 3]]])

both above and below are rehaping techniques

In [92]:
column_vector.reshape(-1,1)

array([[1],
       [2],
       [3]])

In [93]:
row_vector[np.newaxis,:,np.newaxis,np.newaxis].shape

(1, 3, 1, 1)

None behaves like np.newaxis

In [94]:
row_vector[:,None]

array([[1],
       [2],
       [3]])

matrix multiplication

In [95]:
matrix=np.array([[1,2,3],
                [4,5,6]])

column_vector=np.array([[1,2,3]])
column_vector.reshape(-1,1)
column_vector

array([[1, 2, 3]])

In [96]:
np.matmul(matrix,row_vector)

array([14, 32])

In [97]:
np.dot(row_vector,row_vector)

np.int64(14)

In [107]:
np.dot(matrix,row_vector)

array([14, 32])

Transpose

In [108]:
matrix.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [110]:
np.dot(matrix,matrix.transpose())

array([[14, 32],
       [32, 77]])

In [111]:
matrix.T # transpose

array([[1, 4],
       [2, 5],
       [3, 6]])